// Generated by scripts/sync-schema.mjs. Do not edit.
// Source of truth: packages/galaxy-workflow-test-plan-schema/src/galaxy-workflow-test-plan.schema.json.
export const galaxyWorkflowTestPlanSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://foundry.galaxyproject.org/schemas/galaxy-workflow-test-plan.schema.json",
  "title": "Galaxy workflow test plan",
  "description": "Intermediate handoff from source-test translation Molds to implement-galaxy-workflow-test. This is not the final tests-format file.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schema_version",
    "source",
    "tests"
  ],
  "properties": {
    "schema_version": {
      "type": "string",
      "const": "1"
    },
    "source": {
      "$ref": "#/$defs/source_context"
    },
    "workflow": {
      "$ref": "#/$defs/workflow_context"
    },
    "tests": {
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/$defs/test_case"
      }
    },
    "unresolved_mappings": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/unresolved_mapping"
      }
    },
    "omissions": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/omission"
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    }
  },
  "$defs": {
    "source_context": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "nextflow",
            "cwl",
            "paper",
            "other"
          ]
        },
        "summary_artifact": {
          "type": "string",
          "minLength": 1
        },
        "source_path": {
          "type": "string",
          "minLength": 1
        },
        "source_test_id": {
          "type": "string",
          "minLength": 1
        },
        "profile": {
          "type": "string",
          "minLength": 1
        },
        "provenance": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/provenance_item"
          }
        }
      }
    },
    "workflow_context": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "workflow_path": {
          "type": "string",
          "minLength": 1
        },
        "known_input_labels": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "known_output_labels": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "assumptions": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/assumption"
          }
        }
      }
    },
    "test_case": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "job",
        "expected_outputs"
      ],
      "properties": {
        "id": {
          "type": "string",
          "pattern": "^[A-Za-z0-9._-]+$"
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "source_test_id": {
          "type": "string",
          "minLength": 1
        },
        "profile": {
          "type": "string",
          "minLength": 1
        },
        "job": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/job_input"
          }
        },
        "expected_outputs": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/expected_output"
          }
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        },
        "provenance": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/provenance_item"
          }
        }
      }
    },
    "job_input": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "label",
        "value"
      ],
      "properties": {
        "label": {
          "type": "string",
          "minLength": 1
        },
        "value": {},
        "datatype": {
          "type": "string",
          "minLength": 1
        },
        "class": {
          "type": "string",
          "enum": [
            "File",
            "Directory",
            "Collection",
            "scalar"
          ]
        },
        "collection": {
          "$ref": "#/$defs/collection_shape"
        },
        "fixture": {
          "$ref": "#/$defs/fixture"
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "expected_output": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "label",
        "assertions"
      ],
      "properties": {
        "label": {
          "type": "string",
          "minLength": 1
        },
        "datatype": {
          "type": "string",
          "minLength": 1
        },
        "collection": {
          "$ref": "#/$defs/collection_shape"
        },
        "fixture": {
          "$ref": "#/$defs/fixture"
        },
        "assertions": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/$defs/assertion_intent"
          }
        },
        "snapshot_evidence": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/snapshot_evidence"
          }
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "assertion_intent": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "intent"
      ],
      "properties": {
        "intent": {
          "type": "string",
          "minLength": 1
        },
        "tests_format_assertion": {
          "type": "string",
          "minLength": 1
        },
        "params": {
          "type": "object",
          "additionalProperties": true
        },
        "tolerance": {
          "$ref": "#/$defs/tolerance"
        },
        "evidence": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/provenance_item"
          }
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "tolerance": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "exact",
            "absolute",
            "fraction",
            "regex",
            "semantic",
            "manual-review"
          ]
        },
        "value": {},
        "reason": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "fixture": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "path": {
          "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string",
          "format": "uri"
        },
        "checksum": {
          "type": "string",
          "minLength": 1
        },
        "source": {
          "type": "string",
          "minLength": 1
        },
        "provenance": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/provenance_item"
          }
        }
      }
    },
    "collection_shape": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "collection_type"
      ],
      "properties": {
        "collection_type": {
          "type": "string",
          "minLength": 1
        },
        "elements": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": false,
            "required": [
              "identifier"
            ],
            "properties": {
              "identifier": {
                "type": "string",
                "minLength": 1
              },
              "datatype": {
                "type": "string",
                "minLength": 1
              },
              "path": {
                "type": "string",
                "minLength": 1
              }
            }
          }
        }
      }
    },
    "snapshot_evidence": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "value"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "file-list",
            "stable-path",
            "stable-name",
            "checksum",
            "scalar",
            "ignored-file",
            "ignored-glob",
            "other"
          ]
        },
        "value": {},
        "source_path": {
          "type": "string",
          "minLength": 1
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "unresolved_mapping": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "field",
        "reason"
      ],
      "properties": {
        "field": {
          "type": "string",
          "minLength": 1
        },
        "reason": {
          "type": "string",
          "minLength": 1
        },
        "options": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "omission": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "subject",
        "reason"
      ],
      "properties": {
        "subject": {
          "type": "string",
          "minLength": 1
        },
        "reason": {
          "type": "string",
          "minLength": 1
        },
        "evidence": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/provenance_item"
          }
        }
      }
    },
    "assumption": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "subject",
        "assumption"
      ],
      "properties": {
        "subject": {
          "type": "string",
          "minLength": 1
        },
        "assumption": {
          "type": "string",
          "minLength": 1
        },
        "confidence": {
          "type": "string",
          "enum": [
            "high",
            "medium",
            "low"
          ]
        }
      }
    },
    "provenance_item": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "ref"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "source-file",
            "summary-field",
            "snapshot",
            "iwc-exemplar",
            "research-note",
            "manual"
          ]
        },
        "ref": {
          "type": "string",
          "minLength": 1
        },
        "detail": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
} as const;
