#!/usr/bin/env node
// Regenerate per-schema typed-const TS mirrors. JSON is source of truth for
// the three Foundry-authored schemas; for tests-format the source of truth is
// upstream `@galaxy-tool-util/schema` (re-fetched each sync).

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { testsSchema } from "@galaxy-tool-util/schema";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");

function regenerateFromJson(name, exportName) {
  const dir = resolve(PKG_ROOT, "src/schemas", name);
  const src = resolve(dir, `${name}.schema.json`);
  const dst = resolve(dir, `${name}.schema.generated.ts`);
  const schema = JSON.parse(readFileSync(src, "utf8"));
  const banner =
    `// Generated by scripts/sync-schema.mjs. Do not edit.\n` +
    `// Source of truth: packages/foundry/src/schemas/${name}/${name}.schema.json.\n`;
  const body = `export const ${exportName} = ${JSON.stringify(schema, null, 2)} as const;\n`;
  writeFileSync(dst, banner + body);
  console.log(`generated ${dst}`);
}

function regenerateFromUpstream(name, jsonName, exportName, schemaValue, sourceLabel) {
  const dir = resolve(PKG_ROOT, "src/schemas", name);
  const dstJson = resolve(dir, `${jsonName}.json`);
  const dstTs = resolve(dir, `${jsonName}.generated.ts`);
  const json = JSON.stringify(schemaValue, null, 2) + "\n";
  mkdirSync(dirname(dstJson), { recursive: true });
  writeFileSync(dstJson, json);
  const banner =
    `// Generated by scripts/sync-schema.mjs. Do not edit.\n` + `// Source of truth: ${sourceLabel}.\n`;
  writeFileSync(dstTs, `${banner}export const ${exportName} = ${json.trim()} as const;\n`);
  console.log(`synced ${dstJson}`);
  console.log(`generated ${dstTs}`);
}

regenerateFromJson("summary-cwl", "summaryCwlSchema");
regenerateFromJson("galaxy-tool-discovery", "galaxyToolDiscoverySchema");
regenerateFromJson("galaxy-tool-summary", "galaxyToolSummarySchema");
regenerateFromUpstream(
  "tests-format",
  "tests.schema",
  "testsFormatSchema",
  testsSchema,
  "@galaxy-tool-util/schema testsSchema",
);
