#!/usr/bin/env node
// Regenerate the typed-const TS mirror from the canonical
// src/schema/summary-nextflow.schema.json. JSON is source of truth.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");

const SRC_JSON = resolve(PKG_ROOT, "src/schema/summary-nextflow.schema.json");
const DST_TS = resolve(PKG_ROOT, "src/schema/summary-nextflow.schema.generated.ts");

const schema = JSON.parse(readFileSync(SRC_JSON, "utf8"));
const banner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: packages/summarize-nextflow/src/schema/summary-nextflow.schema.json.\n";
const body = `export const summaryNextflowSchema = ${JSON.stringify(schema, null, 2)} as const;\n`;
writeFileSync(DST_TS, banner + body);

console.log(`generated ${DST_TS}`);
