#!/usr/bin/env node
// Regenerate typed-const TS mirrors from this package's canonical JSON sources.
// JSON is vendored from planemo via scripts/sync-from-planemo.mjs (requires
// planemo); this script only rewrites the .ts mirrors and runs on every build
// so contributor laptops never need planemo.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");

const SRC_META = resolve(PKG_ROOT, "src/cli-meta.json");
const SRC_PROVENANCE = resolve(PKG_ROOT, "src/cli-meta.provenance.json");
const DST_META_TS = resolve(PKG_ROOT, "src/cli-meta.generated.ts");
const DST_PROVENANCE_TS = resolve(PKG_ROOT, "src/cli-meta.provenance.generated.ts");

const meta = JSON.parse(readFileSync(SRC_META, "utf8"));
const provenance = JSON.parse(readFileSync(SRC_PROVENANCE, "utf8"));

const banner =
  "// Generated by scripts/sync-meta.mjs. Do not edit.\n" +
  "// Source of truth: src/cli-meta.json (vendored from planemo via\n" +
  "// scripts/sync-from-planemo.mjs).\n";
writeFileSync(
  DST_META_TS,
  banner + `export const planemoCliMeta = ${JSON.stringify(meta, null, 2)} as const;\n`,
);

const provenanceBanner =
  "// Generated by scripts/sync-meta.mjs. Do not edit.\n" +
  "// Source of truth: src/cli-meta.provenance.json.\n";
writeFileSync(
  DST_PROVENANCE_TS,
  provenanceBanner +
    `export const planemoCliMetaProvenance = ${JSON.stringify(provenance, null, 2)} as const;\n`,
);

console.log(`generated ${DST_META_TS}`);
console.log(`generated ${DST_PROVENANCE_TS}`);
