// Generated by scripts/sync-schema.mjs. Do not edit.
// Source of truth: src/test-report.provenance.json.
export const planemoTestReportProvenance = {
  "planemo_version": "0.75.45",
  "schema_name": "test-report",
  "schema_version": "0.1",
  "source": {
    "note": "Released on PyPI; includes merged PR galaxyproject/planemo#1636.",
    "release": "0.75.45",
    "repo": "galaxyproject/planemo"
  }
} as const;
