// Generated by scripts/sync-schema.mjs. Do not edit.
// Source of truth: src/test-report.schema.json (vendored from planemo via
// scripts/sync-from-planemo.mjs).
export const planemoTestReportSchema = {
  "$defs": {
    "PlanemoTestCase": {
      "additionalProperties": true,
      "properties": {
        "data": {
          "anyOf": [
            {
              "$ref": "#/$defs/PlanemoTestCaseData"
            },
            {
              "type": "null"
            }
          ],
          "default": null
        },
        "doc": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Doc"
        },
        "has_data": {
          "title": "Has Data",
          "type": "boolean"
        },
        "id": {
          "title": "Id",
          "type": "string"
        },
        "test_type": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Test Type"
        }
      },
      "required": [
        "id",
        "has_data"
      ],
      "title": "PlanemoTestCase",
      "type": "object"
    },
    "PlanemoTestCaseData": {
      "additionalProperties": true,
      "properties": {
        "end_datetime": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "End Datetime"
        },
        "execution_problem": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Execution Problem"
        },
        "inputs": {
          "anyOf": [
            {
              "additionalProperties": true,
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Inputs"
        },
        "invocation_details": {
          "anyOf": [
            {
              "additionalProperties": true,
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Invocation Details"
        },
        "job": {
          "anyOf": [
            {
              "additionalProperties": true,
              "type": "object"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Job"
        },
        "output_problems": {
          "anyOf": [
            {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Output Problems"
        },
        "problem_log": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Problem Log"
        },
        "start_datetime": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "default": null,
          "title": "Start Datetime"
        },
        "status": {
          "enum": [
            "success",
            "failure",
            "error",
            "skip"
          ],
          "title": "Status",
          "type": "string"
        }
      },
      "required": [
        "status"
      ],
      "title": "PlanemoTestCaseData",
      "type": "object"
    },
    "PlanemoTestSummary": {
      "additionalProperties": true,
      "properties": {
        "num_errors": {
          "title": "Num Errors",
          "type": "integer"
        },
        "num_failures": {
          "title": "Num Failures",
          "type": "integer"
        },
        "num_skips": {
          "title": "Num Skips",
          "type": "integer"
        },
        "num_tests": {
          "title": "Num Tests",
          "type": "integer"
        }
      },
      "required": [
        "num_tests",
        "num_failures",
        "num_skips",
        "num_errors"
      ],
      "title": "PlanemoTestSummary",
      "type": "object"
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": true,
  "properties": {
    "exit_code": {
      "anyOf": [
        {
          "type": "integer"
        },
        {
          "type": "null"
        }
      ],
      "default": null,
      "title": "Exit Code"
    },
    "summary": {
      "anyOf": [
        {
          "$ref": "#/$defs/PlanemoTestSummary"
        },
        {
          "type": "null"
        }
      ],
      "default": null
    },
    "tests": {
      "items": {
        "$ref": "#/$defs/PlanemoTestCase"
      },
      "title": "Tests",
      "type": "array"
    },
    "version": {
      "default": "0.1",
      "title": "Version",
      "type": "string"
    }
  },
  "required": [
    "tests"
  ],
  "title": "PlanemoTestReport",
  "type": "object"
} as const;
