// Generated by scripts/sync-schema.mjs. Do not edit.
// Source of truth: src/test-report.provenance.json.
export const planemoTestReportProvenance = {
  "planemo_version": "0.75.42.dev0",
  "schema_name": "test-report",
  "schema_version": "0.1",
  "source": {
    "branch": "workflow_work",
    "note": "Pre-merge of upstream PR galaxyproject/planemo#1636. Unpin once upstream merges + releases.",
    "repo": "jmchilton/planemo",
    "sha": "a9b8b8bc7ab3b12035d53bdb5383fe450413d9f3"
  }
} as const;
