// Generated by scripts/sync-meta.mjs. Do not edit.
// Source of truth: src/cli-meta.provenance.json.
export const planemoCliMetaProvenance = {
  "planemo_version": "0.75.45",
  "schema_version": "0.1",
  "source": {
    "note": "Released on PyPI; includes merged PR galaxyproject/planemo#1636.",
    "release": "0.75.45",
    "repo": "galaxyproject/planemo"
  }
} as const;
