#!/usr/bin/env node
// Regenerate typed-const TS mirrors from this package's canonical JSON sources.
// Schema JSON + provenance JSON are vendored from upstream planemo via
// `scripts/sync-from-planemo.mjs` (requires planemo); this script only rewrites
// the .ts mirrors and runs on every build so contributor laptops never need
// planemo.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");

const SRC_SCHEMA = resolve(PKG_ROOT, "src/test-report.schema.json");
const SRC_PROVENANCE = resolve(PKG_ROOT, "src/test-report.provenance.json");
const DST_SCHEMA_TS = resolve(PKG_ROOT, "src/test-report.schema.generated.ts");
const DST_PROVENANCE_TS = resolve(PKG_ROOT, "src/test-report.provenance.generated.ts");

const schema = JSON.parse(readFileSync(SRC_SCHEMA, "utf8"));
const provenance = JSON.parse(readFileSync(SRC_PROVENANCE, "utf8"));

const banner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: src/test-report.schema.json (vendored from planemo via\n" +
  "// scripts/sync-from-planemo.mjs).\n";

writeFileSync(
  DST_SCHEMA_TS,
  banner + `export const planemoTestReportSchema = ${JSON.stringify(schema, null, 2)} as const;\n`,
);

const provenanceBanner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: src/test-report.provenance.json.\n";

writeFileSync(
  DST_PROVENANCE_TS,
  provenanceBanner +
    `export const planemoTestReportProvenance = ${JSON.stringify(provenance, null, 2)} as const;\n`,
);

console.log(`generated ${DST_SCHEMA_TS}`);
console.log(`generated ${DST_PROVENANCE_TS}`);
