// Generated by scripts/sync-schema.mjs. Do not edit.
// Source of truth: packages/gxwf-foundry/src/schemas/workflow-brief/workflow-brief.schema.json.
export const workflowBriefSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Workflow Brief (proposal)",
  "description": "Versioned scope, requirements, and intended environment for a workflow. Structure validation does not establish approval or runtime readiness.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "brief_version",
    "id",
    "revision",
    "title",
    "sources",
    "scope",
    "interface",
    "constraints",
    "environment",
    "acceptance",
    "questions",
    "decisions",
    "learning",
    "artifacts"
  ],
  "properties": {
    "brief_version": {
      "type": "string",
      "const": "1"
    },
    "id": {
      "type": "string",
      "minLength": 1
    },
    "revision": {
      "type": "integer",
      "minimum": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "sources": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Source"
      },
      "minItems": 1,
      "description": "Source evidence and the selected analyses or branches; availability is declared, not probed."
    },
    "scope": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "objective",
        "in_scope",
        "out_of_scope"
      ],
      "properties": {
        "objective": {
          "type": "string",
          "minLength": 1
        },
        "in_scope": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "minItems": 1
        },
        "out_of_scope": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      },
      "description": "Scientific objective and explicit included and excluded work."
    },
    "interface": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "inputs",
        "outputs"
      ],
      "properties": {
        "inputs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/InterfaceItem"
          }
        },
        "outputs": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/InterfaceItem"
          }
        }
      },
      "description": "Desired input and output roles; IDs need not be final Galaxy workflow labels."
    },
    "constraints": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Constraint"
      },
      "description": "Mandatory requirements or preferences, with rationale and source evidence IDs."
    },
    "environment": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "authoring",
        "execution"
      ],
      "properties": {
        "authoring": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "tools",
            "workspace",
            "network_policy"
          ],
          "properties": {
            "tools": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ToolRequirement"
              }
            },
            "workspace": {
              "type": [
                "string",
                "null"
              ],
              "minLength": 1
            },
            "network_policy": {
              "type": [
                "string",
                "null"
              ],
              "minLength": 1
            }
          }
        },
        "execution": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "target",
            "galaxy_mode",
            "galaxy_location",
            "galaxy_version",
            "container_policy",
            "tools",
            "reference_assets",
            "writable_locations",
            "resource_limits"
          ],
          "properties": {
            "target": {
              "type": "string",
              "enum": [
                "galaxy",
                "cwl",
                "undecided"
              ]
            },
            "galaxy_mode": {
              "type": "string",
              "enum": [
                "managed",
                "external",
                "not-applicable",
                "undecided"
              ]
            },
            "galaxy_location": {
              "type": [
                "string",
                "null"
              ],
              "minLength": 1
            },
            "galaxy_version": {
              "type": [
                "string",
                "null"
              ],
              "minLength": 1
            },
            "container_policy": {
              "type": "string",
              "enum": [
                "required",
                "allowed",
                "forbidden",
                "undecided"
              ]
            },
            "tools": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ToolRequirement"
              }
            },
            "reference_assets": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/ReferenceAsset"
              }
            },
            "writable_locations": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            },
            "resource_limits": {
              "type": [
                "string",
                "null"
              ],
              "minLength": 1
            }
          }
        }
      },
      "description": "Intended authoring and execution environments; observed readiness belongs in a separate preflight result."
    },
    "acceptance": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Criterion"
      },
      "minItems": 1,
      "description": "Observable success criteria; detailed test cases remain in the existing test-plan handoff."
    },
    "questions": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Question"
      },
      "description": "Unresolved choices and eventual resolutions; blocks names the stages affected."
    },
    "decisions": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Decision"
      },
      "description": "Expert choices with rationale and source evidence IDs."
    },
    "learning": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Learning"
      },
      "description": "Attempt-specific observations and implications, linked to evidence; not automatic requirement changes."
    },
    "artifacts": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/Artifact"
      },
      "description": "Linked detailed handoffs, preserving source-specific evidence and implementation artifacts."
    }
  },
  "$defs": {
    "Source": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "kind",
        "location",
        "pin",
        "availability",
        "selected_sections"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "kind": {
          "type": "string",
          "enum": [
            "paper",
            "interview",
            "nextflow",
            "cwl",
            "galaxy",
            "other"
          ]
        },
        "location": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "pin": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "availability": {
          "type": "string",
          "enum": [
            "available",
            "missing",
            "unverified"
          ]
        },
        "selected_sections": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "InterfaceItem": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "description",
        "datatype",
        "shape",
        "evidence_ids"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "datatype": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "shape": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "evidence_ids": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "Constraint": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "requirement",
        "strength",
        "rationale",
        "evidence_ids"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "requirement": {
          "type": "string",
          "minLength": 1
        },
        "strength": {
          "type": "string",
          "enum": [
            "must",
            "prefer"
          ]
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        },
        "evidence_ids": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "ToolRequirement": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "version",
        "provisioning"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "version": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "provisioning": {
          "type": "string",
          "enum": [
            "preinstalled",
            "install",
            "container",
            "undecided"
          ]
        }
      }
    },
    "ReferenceAsset": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "description",
        "location",
        "pin",
        "provisioning"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "location": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "pin": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "provisioning": {
          "type": "string",
          "enum": [
            "provided",
            "download",
            "build",
            "undecided"
          ]
        }
      }
    },
    "Criterion": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "description",
        "basis",
        "fixture",
        "expected",
        "evidence_ids"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "basis": {
          "type": "string",
          "enum": [
            "source-evidence",
            "expert-requirement",
            "assumption"
          ]
        },
        "fixture": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "expected": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "evidence_ids": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "Question": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "question",
        "blocks",
        "resolution",
        "evidence_ids"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "question": {
          "type": "string",
          "minLength": 1
        },
        "blocks": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "implementation",
              "execution"
            ]
          }
        },
        "resolution": {
          "type": [
            "string",
            "null"
          ],
          "minLength": 1
        },
        "evidence_ids": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "Decision": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "decision",
        "rationale",
        "evidence_ids"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "decision": {
          "type": "string",
          "minLength": 1
        },
        "rationale": {
          "type": "string",
          "minLength": 1
        },
        "evidence_ids": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "Learning": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "attempt_id",
        "observation",
        "implication",
        "evidence_locations"
      ],
      "properties": {
        "attempt_id": {
          "type": "string",
          "minLength": 1
        },
        "observation": {
          "type": "string",
          "minLength": 1
        },
        "implication": {
          "type": "string",
          "minLength": 1
        },
        "evidence_locations": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        }
      }
    },
    "Artifact": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind",
        "location"
      ],
      "properties": {
        "kind": {
          "type": "string",
          "enum": [
            "source-summary",
            "interface-brief",
            "data-flow-brief",
            "reference-data-brief",
            "draft-workflow",
            "test-plan",
            "other"
          ]
        },
        "location": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  },
  "$id": "https://galaxyproject.org/foundry/schemas/workflow-brief.schema.json",
  "$comment": "RFC/WIP: agent-written rough draft for review in galaxyproject/foundry#563. Canonical JSON Schema; validates YAML structure, not approval or stage readiness."
} as const;
