// Generated by scripts/generate-workflow-brief-types.mjs. Do not edit.
export type WorkflowBrief = {
  brief_version: "1";
  id: string;
  revision: number;
  title: string;
  sources: Array<WorkflowBriefSource>;
  scope: {
    objective: string;
    in_scope: Array<string>;
    out_of_scope: Array<string>;
  };
  interface: {
    inputs: Array<WorkflowBriefInterfaceItem>;
    outputs: Array<WorkflowBriefInterfaceItem>;
  };
  constraints: Array<WorkflowBriefConstraint>;
  environment: {
    authoring: {
      tools: Array<WorkflowBriefToolRequirement>;
      workspace: string | null;
      network_policy: string | null;
    };
    execution: {
      target: "galaxy" | "cwl" | "undecided";
      galaxy_mode: "managed" | "external" | "not-applicable" | "undecided";
      galaxy_location: string | null;
      galaxy_version: string | null;
      container_policy: "required" | "allowed" | "forbidden" | "undecided";
      tools: Array<WorkflowBriefToolRequirement>;
      reference_assets: Array<WorkflowBriefReferenceAsset>;
      writable_locations: Array<string>;
      resource_limits: string | null;
    };
  };
  acceptance: Array<WorkflowBriefCriterion>;
  questions: Array<WorkflowBriefQuestion>;
  decisions: Array<WorkflowBriefDecision>;
  learning: Array<WorkflowBriefLearning>;
  artifacts: Array<WorkflowBriefArtifact>;
};

export type WorkflowBriefSource = {
  id: string;
  kind: "paper" | "interview" | "nextflow" | "cwl" | "galaxy" | "other";
  location: string | null;
  pin: string | null;
  availability: "available" | "missing" | "unverified";
  selected_sections: Array<string>;
};

export type WorkflowBriefInterfaceItem = {
  id: string;
  description: string;
  datatype: string | null;
  shape: string | null;
  evidence_ids: Array<string>;
};

export type WorkflowBriefConstraint = {
  id: string;
  requirement: string;
  strength: "must" | "prefer";
  rationale: string;
  evidence_ids: Array<string>;
};

export type WorkflowBriefToolRequirement = {
  name: string;
  version: string | null;
  provisioning: "preinstalled" | "install" | "container" | "undecided";
};

export type WorkflowBriefReferenceAsset = {
  id: string;
  description: string;
  location: string | null;
  pin: string | null;
  provisioning: "provided" | "download" | "build" | "undecided";
};

export type WorkflowBriefCriterion = {
  id: string;
  description: string;
  basis: "source-evidence" | "expert-requirement" | "assumption";
  fixture: string | null;
  expected: string | null;
  evidence_ids: Array<string>;
};

export type WorkflowBriefQuestion = {
  id: string;
  question: string;
  blocks: Array<"implementation" | "execution">;
  resolution: string | null;
  evidence_ids: Array<string>;
};

export type WorkflowBriefDecision = {
  id: string;
  decision: string;
  rationale: string;
  evidence_ids: Array<string>;
};

export type WorkflowBriefLearning = {
  attempt_id: string;
  observation: string;
  implication: string;
  evidence_locations: Array<string>;
};

export type WorkflowBriefArtifact = {
  kind:
    | "source-summary"
    | "interface-brief"
    | "data-flow-brief"
    | "reference-data-brief"
    | "draft-workflow"
    | "test-plan"
    | "other";
  location: string;
};
